name: Build Desktop EXE
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Force Standalone Mode
        # This deletes the files that are causing the "Workspace" error
        run: |
          rm pnpm-workspace.yaml
          rm pnpm-lock.yaml

      - name: Install Dependencies
        run: |
          cd apps/client
          pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Build Web App
        run: |
          cd apps/client
          npx next build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: Build Tauri EXE
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/client
          tagName: v1.0.7
          releaseName: "Local Offline Build"
